import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/components/Form'
import Footer from '@/components/Footer'
import SignUp from '@/components/SignUp'
import GetApp from '@/components/GetApp'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Form />
        <SignUp />
        <GetApp />
      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}
